module.exports=Object.freeze({
    MY_SALT:'ThisIsMySalt',
    MY_SALT_ROUND:10,
    TOEKN_EXPIRY_TIME:'60m',
    ID_INITIALIZATION:0,
    DB_NAME:'ecommerce',
    DB_USER:'root',
    DB_PASSWORD:'nived@99#'
})